//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VBA.rc
//
#define IDS_CANNOT_LOAD_SGM             2
#define IDS_SAVE_GAME_NOT_USING_BIOS    3
#define IDS_SAVE_GAME_USING_BIOS        4
#define IDS_UNSUPPORTED_SAVE_TYPE       5
#define IDS_CANNOT_OPEN_FILE            6
#define IDS_BAD_ZIP_FILE                7
#define IDS_NO_IMAGE_ON_ZIP             8
#define IDS_ERROR_OPENING_IMAGE         9
#define IDS_ERROR_READING_IMAGE         10
#define IDS_UNSUPPORTED_BIOS_FUNCTION   11
#define IDS_INVALID_BIOS_FILE_SIZE      12
#define IDS_INVALID_CHEAT_CODE          13
#define IDS_UNKNOWN_ARM_OPCDOE          14
#define IDS_UNKNOWN_THUMB_OPCODE        15
#define IDS_ERROR_CREATING_FILE         16
#define IDS_FAILED_TO_READ_SGM          17
#define IDS_FAILED_TO_READ_RTC          18
#define IDS_UNSUPPORTED_VB_SGM          19
#define IDS_CANNOT_LOAD_SGM_FOR         20
#define IDS_ERROR_OPENING_IMAGE_FROM    21
#define IDS_ERROR_READING_IMAGE_FROM    22
#define IDS_UNSUPPORTED_ROM_SIZE        23
#define IDS_UNSUPPORTED_RAM_SIZE        24
#define IDS_UNKNOWN_CARTRIDGE_TYPE      25
#define IDS_MAXIMUM_NUMBER_OF_CHEATS    26
#define IDS_INVALID_GAMESHARK_CODE      27
#define IDS_INVALID_GAMEGENIE_CODE      28
#define IDS_INVALID_CHEAT_TO_REMOVE     29
#define IDS_INVALID_CHEAT_CODE_ADDRESS  30
#define IDS_UNSUPPORTED_CHEAT_LIST_VERSION 31
#define IDS_UNSUPPORTED_CHEAT_LIST_TYPE 32
#define IDS_INVALID_GSA_CODE            33
#define IDS_CANNOT_IMPORT_SNAPSHOT_FOR  34
#define IDS_UNSUPPORTED_SNAPSHOT_FILE   35
#define IDS_UNSUPPORTED_ARM_MODE        36
#define IDS_UNSUPPORTED_CODE_FILE       37
#define IDS_GSA_CODE_WARNING            38
#define IDS_INVALID_CBA_CODE            39
#define IDS_CBA_CODE_WARNING            40
#define IDS_OUT_OF_MEMORY               41
#define IDS_STRING42                    42
#define IDS_UNSUPPORTED_VBA_SGM         43
#define IDS_DIRECTX_7_REQUIRED          44
#define IDS_DISABLING_VIDEO_MEMORY      45
#define IDS_SETTING_WILL_BE_EFFECTIVE   46
#define IDS_DISABLING_EMULATION_ONLY    47
#define IDS_FAILED_TO_OPEN_FILE         48
#define IDS_FAILED_TO_READ_ZIP_DIR      49
#define IDS_UNSUPPORTED_FILE_TYPE       50
#define IDS_CANNOT_CREATE_DIRECTSOUND   51
#define IDS_CANNOT_SETCOOPERATIVELEVEL  52
#define IDS_CANNOT_CREATESOUNDBUFFER    53
#define IDS_CANNOT_SETFORMAT_PRIMARY    54
#define IDS_CANNOT_CREATESOUNDBUFFER_SEC 55
#define IDS_CANNOT_PLAY_PRIMARY         56
#define IDS_SEARCH_PRODUCED_TOO_MANY    57
#define IDS_NUMBER_CANNOT_BE_EMPTY      58
#define IDS_INVALID_ADDRESS             59
#define IDS_MISALIGNED_HALFWORD         60
#define IDS_MISALIGNED_WORD             61
#define IDS_VALUE_CANNOT_BE_EMPTY       62
#define IDS_ERROR_ON_STARTDOC           63
#define IDS_ERROR_ON_STARTPAGE          64
#define IDS_ERROR_PRINTING_ON_STRETCH   65
#define IDS_ERROR_ON_ENDPAGE            66
#define IDS_ERROR_ON_ENDDOC             67
#define IDS_ERROR                       68
#define IDS_JOY_LEFT                    69
#define IDS_JOY_RIGHT                   70
#define IDS_JOY_UP                      71
#define IDS_JOY_DOWN                    72
#define IDS_JOY_BUTTON                  73
#define IDS_SELECT_BIOS_FILE            74
#define IDS_RESET                       75
#define IDS_AUTOFIRE_A_DISABLED         76
#define IDS_AUTOFIRE_A                  77
#define IDS_AUTOFIRE_B_DISABLED         78
#define IDS_AUTOFIRE_B                  79
#define IDS_AUTOFIRE_L_DISABLED         80
#define IDS_AUTOFIRE_L                  81
#define IDS_AUTOFIRE_R_DISABLED         82
#define IDS_AUTOFIRE_R                  83
#define IDS_SELECT_ROM                  84
#define IDS_SELECT_SAVE_GAME_NAME       85
#define IDS_LOADED_STATE                86
#define IDS_LOADED_STATE_N              87
#define IDS_WROTE_STATE                 88
#define IDS_WROTE_STATE_N               89
#define IDS_LOADED_BATTERY              90
#define IDS_SELECT_CAPTURE_NAME         91
#define IDS_SCREEN_CAPTURE              92
#define IDS_ADDRESS                     93
#define IDS_OLD_VALUE                   94
#define IDS_NEW_VALUE                   95
#define IDS_ADD_CHEAT_CODE              96
#define IDS_CODE                        97
#define IDS_DESCRIPTION                 98
#define IDS_STATUS                      99
#define IDS_FAILED_TO_LOAD_LIBRARY      100
#define IDS_FAILED_TO_GET_LOCINFO       101
#define IDS_SELECT_CHEAT_LIST_NAME      102
#define IDS_FILTER_BIOS                 103
#define IDS_FILTER_ROM                  104
#define IDS_FILTER_SGM                  105
#define IDS_FILTER_CHEAT_LIST           106
#define IDS_FILTER_PNG                  107
#define IDS_FILTER_SPS                  108
#define IDS_SELECT_SNAPSHOT_FILE        109
#define IDS_FILTER_SAV                  110
#define IDS_SELECT_BATTERY_FILE         111
#define IDS_FILTER_GBS                  112
#define IDS_FILTER_GCF                  113
#define IDS_SELECT_CODE_FILE            114
#define IDS_SAVE_WILL_BE_LOST           115
#define IDS_CONFIRM_ACTION              116
#define IDS_CODES_WILL_BE_LOST          117
#define IDS_FILTER_SPC                  118
#define IDS_ADD_CBA_CODE                119
#define IDS_FILTER_WAV                  120
#define IDS_SELECT_WAV_NAME             121
#define IDS_FILTER_GBROM                122
#define IDS_FILTER_PAL                  123
#define IDS_SELECT_PALETTE_NAME         124
#define IDS_SEARCH_PRODUCED_NO_RESULTS  125
#define IDS_ERROR_BINDING               126
#define IDS_ERROR_LISTENING             127
#define IDS_ERROR_CREATING_SOCKET       128
#define IDS_ACK_NOT_RECEIVED            129
#define IDS_ERROR_NOT_GBA_IMAGE         130
#define IDS_EEPROM_NOT_SUPPORTED        131
#define IDS_FILTER_DUMP                 132
#define IDS_SELECT_DUMP_FILE            133
#define IDS_FILTER_AVI                  134
#define IDS_SELECT_AVI_NAME             135
#define IDS_INVALID_THROTTLE_VALUE      136
#define IDS_FILTER_INI                  137
#define IDS_SELECT_SKIN_FILE            138
#define IDS_FILTER_MOVIE                139
#define IDS_FILTER_VMV                  140
#define IDS_SELECT_MOVIE_NAME           141
#define IDS_BUG_REPORT                  142
#define IDS_UNSUPPORTED_MOVIE_VERSION   143
#define IDS_END_OF_MOVIE                144
#define IDS_INVALID_INTERVAL_VALUE      145
#define IDS_REGISTRY                    146
#define IDS_MOVIE_PLAY                  147
#define IDS_AUTOFIRE_DISABLED           148
#define IDS_AUTOFIRE_ALREADY_DISABLED   149
#define IDS_AUTOFIRE_START_DISABLED     150
#define IDS_AUTOFIRE_START              151
#define IDS_AUTOFIRE_SELECT_DISABLED    152
#define IDS_AUTOFIRE_SELECT             153
#define IDS_AUTOFIRE_UP_DISABLED        154
#define IDS_AUTOFIRE_UP                 155
#define IDS_AUTOFIRE_DOWN_DISABLED      156
#define IDS_AUTOFIRE_DOWN               157
#define IDS_AUTOFIRE_LEFT_DISABLED      158
#define IDS_AUTOFIRE_LEFT               159
#define IDS_AUTOFIRE_RIGHT_DISABLED     160
#define IDS_AUTOFIRE_RIGHT              161
#define IDS_RERECORDED_STATE_N          162
#define IDS_REPLAYED_STATE_N            163
#define IDS_LOADED_CHEATS               164
#define IDS_ADD_GG_CODE                 165
#define IDS_ADD_GS_CODE                 166
#define IDS_ADD_GSA_CODE                167
#define IDS_POCKET_PRINTER              168
#define IDS_UNKNOWN                     169
#define IDS_NONE                        170
#define IDS_ERROR_DISP_COLOR            171
#define IDS_SELECT_MOVIE_DIR            172
#define IDS_SELECT_ROM_DIR              173
#define IDS_SELECT_GBXROM_DIR           174
#define IDS_SELECT_BATTERY_DIR          175
#define IDS_SELECT_SAVE_DIR             176
#define IDS_SELECT_CAPTURE_DIR          177
#define IDS_SELECT_AVI_DIR              178
#define IDS_SELECT_WAV_DIR              179
#define IDS_SELECT_CHEAT_DIR            180
#define IDS_SELECT_WATCH_DIR            181
#define IDS_SELECT_IPS_DIR              182
#define IDS_SELECT_PLUGIN_DIR           183
#define IDS_FILTER_LUA                  184
#define IDS_SELECT_LUA_NAME             185
#define IDS_SELECT_LUA_DIR              186
#define IDS_STARTAVIRECORDING           187
#define IDS_STOPAVIRECORDING            188
#define IDS_PAUSEAVIRECORDING           189
#define IDS_RESUMEAVIRECORDING          190
#define IDS_STARTSOUNDRECORDING         191
#define IDS_STOPSOUNDRECORDING          192
#define IDR_MENU                        401
#define IDR_ACCELERATOR                 405
#define IDR_GB_PRINTER                  406
#define IDR_ACCELERATOR1                407
#define IDI_ICON                        451
#define IDD_REGISTERS                   502
#define IDD_DEBUG                       503
#define IDD_ABOUT                       505
#define IDD_CHEATS                      507
#define IDD_ADD_CHEAT                   508
#define IDD_DIRECTORIES                 509
#define IDD_CONFIG                      510
#define IDD_GS                          511
#define IDD_GG                          512
#define IDD_CHEAT_LIST                  513
#define IDD_ASSOCIATIONS                514
#define IDD_GBA_ROM_INFO                516
#define IDD_GB_ROM_INFO                 517
#define IDD_GB_CHEAT_LIST               518
#define IDD_ADD_CHEAT_DLG               519
#define IDD_GB_PRINTER                  520
#define IDD_MOTION_CONFIG               521
#define IDD_LANG_SELECT                 522
#define IDD_CODE_SELECT                 523
#define IDD_OPENDLG                     524
#define IDD_MAP_VIEW                    526
#define IDD_PALETTE_VIEW                527
#define IDD_MEM_VIEWER                  528
#define IDD_OAM_VIEW                    530
#define IDD_ACCEL_EDITOR                531
#define IDD_TILE_VIEWER                 532
#define IDD_GB_COLORS                   533
#define IDD_DISASSEMBLE                 534
#define IDD_GDB_PORT                    535
#define IDD_GDB_WAITING                 536
#define IDD_LOGGING                     537
#define IDD_EXPORT_SPS                  538
#define IDD_ADDR_SIZE                   539
#define IDD_MODES                       540
#define IDD_DRIVERS                     542
#define IDD_THROTTLE                    543
#define IDD_GB_DISASSEMBLE              544
#define IDD_GB_OAM_VIEW                 545
#define IDD_GB_TILE_VIEWER              546
#define IDD_GB_MAP_VIEW                 547
#define IDD_GB_PALETTE_VIEW             548
#define IDD_MODE_CONFIRM                549
#define IDD_REWIND_INTERVAL             550
#define IDD_IO_VIEWER                   551
#define IDD_MAX_SCALE                   554
#define IDD_BUG_REPORT                  555
#define IDD_MOVIECREATE                 556
#define IDD_MOVIEOPEN                   557
#define IDD_TEXTCONFIG                  558
#define IDD_LUA                         559
#define IDD_ARCHIVEFILECHOOSER          560
#define IDD_RAMSEARCH                   561
#define IDD_EDITWATCH                   562
#define IDD_RAMWATCH                    563
#define IDD_PROMPT                      564
#define IDC_R0                          1000
#define IDC_R1                          1001
#define IDC_R2                          1002
#define IDC_R3                          1003
#define IDC_R4                          1004
#define IDC_R5                          1005
#define IDC_R6                          1006
#define IDC_R7                          1007
#define IDC_R8                          1008
#define IDC_R9                          1009
#define IDC_R10                         1010
#define IDC_R11                         1011
#define IDC_R12                         1012
#define IDC_R13                         1013
#define IDC_R14                         1014
#define IDC_R15                         1015
#define IDC_R16                         1016
#define IDC_NEXT                        1021
#define IDC_CONTINUE                    1022
#define IDC_CHEAT_LIST                  1023
#define IDC_START                       1024
#define IDC_SEARCH                      1025
#define IDC_OLD_VALUE                   1026
#define IDC_SPECIFIC_VALUE              1027
#define IDC_SIZE_8                      1028
#define IDC_SIZE_16                     1029
#define IDC_SIZE_32                     1030
#define IDC_EQ                          1031
#define IDC_NE                          1032
#define IDC_LT                          1033
#define IDC_LE                          1034
#define IDC_GT                          1035
#define IDC_GE                          1036
#define IDC_SIGNED                      1037
#define IDC_UNSIGNED                    1038
#define IDC_HEXADECIMAL                 1040
#define IDC_VALUE                       1041
#define IDC_ADDRESS                     1042
#define IDC_R                           1043
#define IDC_G                           1044
#define IDC_B                           1045
#define IDC_UPDATE                      1046
#define IDC_GGDESC                      1047
#define IDC_GGCODE                      1048
#define IDC_GGADD                       1049
#define IDC_GGDEL                       1050
#define IDC_GGLIST                      1051
#define IDC_GGRES                       1052
#define IDC_GGQUIT                      1053
#define IDC_GSDESC                      1054
#define IDC_GSCODE                      1055
#define IDC_GSADD                       1056
#define IDC_GSDEL                       1057
#define IDC_GSLIST                      1058
#define IDC_GSRES                       1059
#define IDC_GSQUIT                      1060
#define IDC_FREEZE                      1061
#define IDC_REMOVE                      1062
#define IDC_REMOVE_ALL                  1063
#define IDC_ENABLE                      1064
#define IDC_RESTORE                     1065
#define IDC_GBA                         1066
#define IDC_AGB                         1067
#define IDC_BIN                         1068
#define IDC_GB                          1069
#define IDC_SGB                         1070
#define IDC_CGB                         1071
#define IDC_GBC                         1072
#define IDC_CODE                        1073
#define IDC_DESC                        1074
#define IDC_ROM_TITLE                   1079
#define IDC_ROM_GAME_CODE               1080
#define IDC_ROM_MAKER_CODE              1081
#define IDC_ROM_UNIT_CODE               1082
#define IDC_ROM_DEVICE_TYPE             1083
#define IDC_ROM_VERSION                 1084
#define IDC_ROM_CRC                     1085
#define IDC_ROM_MAKER_NAME              1086
#define IDC_ROM_COLOR                   1087
#define IDC_ROM_SIZE                    1088
#define IDC_ROM_RAM_SIZE                1089
#define IDC_ROM_DEST_CODE               1090
#define IDC_ROM_LIC_CODE                1091
#define IDC_ROM_CHECKSUM                1092
#define IDC_ROM_MAKER_NAME2             1093
#define IDC_GB_PRINTER                  1094
#define IDC_TRANSLATION_BY              1096
#define IDC_LANG_STRING                 1097
#define IDC_LANG_NAME                   1098
#define IDC_GAME_LIST                   1099
#define IDC_1X                          1100
#define IDC_2X                          1101
#define IDC_3X                          1102
#define IDC_4X                          1103
#define IDC_ADD_GG_CHEAT                1104
#define IDC_ADD_GSA                     1105
#define IDC_ADD_CODE                    1106
#define IDC_ADD_CODEBREAKER             1107
#define IDC_FRAME_0                     1113
#define IDC_FRAME_1                     1114
#define IDC_BG0                         1115
#define IDC_BG1                         1116
#define IDC_BG2                         1117
#define IDC_BG3                         1118
#define IDC_MAP_VIEW                    1120
#define IDC_PALETTE_VIEW                1121
#define IDC_PALETTE_VIEW_OBJ            1122
#define IDC_SAVE                        1123
#define IDC_GOPC                        1124
#define IDC_APPLY                       1125
#define IDC_REFRESH                     1126
#define IDC_REFRESH2                    1127
#define IDC_CLOSE                       1128
#define IDC_COLOR                       1129
#define IDC_SAVE_BG                     1130
#define IDC_SAVE_OBJ                    1131
#define IDC_MAP_VIEW_ZOOM               1132
#define IDC_VIEWER                      1133
#define IDC_ADDRESSES                   1134
#define IDC_GO                          1135
#define IDC_8_BIT                       1136
#define IDC_16_BIT                      1137
#define IDC_32_BIT                      1138
#define IDC_OAM_VIEW                    1139
#define IDC_OAM_VIEW_ZOOM               1140
#define IDC_SPRITE                      1141
#define IDC_POS                         1142
#define IDC_MODE                        1143
#define IDC_COLORS                      1144
#define IDC_MAPBASE                     1145
#define IDC_PALETTE                     1146
#define IDC_CHARBASE                    1147
#define IDC_TILE                        1148
#define IDC_DIM                         1149
#define IDC_PRIO                        1150
#define IDC_NUMCOLORS                   1151
#define IDC_SCROLLBAR                   1152
#define IDC_PRIORITY                    1153
#define IDC_MOSAIC                      1154
#define IDC_SIZE2                       1155
#define IDC_OVERFLOW                    1156
#define IDC_ROT                         1157
#define IDC_FLAGS                       1158
#define IDC_COMMANDS                    1159
#define IDC_BANK                        1160
#define IDC_CURRENTS                    1161
#define IDC_ASSIGN                      1162
#define IDC_RESET                       1163
#define IDC_EDIT_KEY                    1164
#define IDC_PALETTE_SLIDER              1165
#define IDC_TILE_VIEW                   1166
#define IDC_ALREADY_AFFECTED            1167
#define IDC_16_COLORS                   1168
#define IDC_256_COLORS                  1169
#define IDC_CHARBASE_0                  1170
#define IDC_CHARBASE_1                  1171
#define IDC_CHARBASE_2                  1172
#define IDC_CHARBASE_3                  1173
#define IDC_CHARBASE_4                  1174
#define IDC_COLOR_BG0                   1175
#define IDC_COLOR_BG1                   1176
#define IDC_COLOR_BG2                   1177
#define IDC_COLOR_BG3                   1178
#define IDC_COLOR_OB0                   1179
#define IDC_COLOR_OB1                   1180
#define IDC_COLOR_OB2                   1181
#define IDC_COLOR_OB3                   1182
#define IDC_STATIC1                     1183
#define IDC_STATIC2                     1184
#define IDC_STATIC3                     1185
#define IDC_STATIC4                     1186
#define IDC_URL                         1187
#define IDC_STRETCH                     1188
#define IDC_TRANSLATOR_URL              1189
#define IDC_DEFAULT                     1191
#define IDC_USER1                       1192
#define IDC_USER2                       1193
#define IDC_DISASSEMBLE                 1196
#define IDC_AUTOMATIC                   1199
#define IDC_ARM                         1200
#define IDC_THUMB                       1201
#define IDC_AUTO_UPDATE                 1204
#define IDC_N                           1210
#define IDC_Z                           1211
#define IDC_C                           1212
#define IDC_V                           1213
#define IDC_F                           1214
#define IDC_I                           1215
#define IDC_T                           1216
#define IDC_PORT                        1217
#define IDC_VSCROLL                     1218
#define IDC_LOG                         1219
#define IDC_CLEAR                       1220
#define IDC_TILE_NUMBER                 1221
#define IDC_XY                          1222
#define IDC_VERBOSE_SWI                 1223
#define IDC_VERBOSE_UNALIGNED_ACCESS    1224
#define IDC_VERBOSE_ILLEGAL_WRITE       1225
#define IDC_VERBOSE_ILLEGAL_READ        1226
#define IDC_VERBOSE_DMA0                1227
#define IDC_VERBOSE_DMA1                1228
#define IDC_VERBOSE_DMA2                1229
#define IDC_VERBOSE_DMA3                1230
#define IDC_VERBOSE_UNDEFINED           1231
#define IDC_VERBOSE_AGBPRINT            1232
#define IDC_CURRENT_ADDRESS             1233
#define IDC_CURRENT_ADDRESS_LABEL       1234
#define IDC_TITLE                       1235
#define IDC_NOTES                       1236
#define IDC_LOAD                        1238
#define IDC_SIZE_CONTROL                1239
#define IDC_MODES                       1240
#define IDC_DRIVERS                     1241
#define IDC_THROTTLE                    1242
#define IDC_H                           1243
#define IDC_OAP                         1244
#define IDC_BANK_0                      1245
#define IDC_BANK_1                      1246
#define IDC_TIMER                       1247
#define IDC_INTERVAL                    1248
#define IDC_REWINDSLOTS                 1249
#define IDC_PREDEFINED                  1251
#define IDC_BUG_REPORT                  1252
#define IDC_COPY                        1253
#define IDC_BROWSE                      1254
#define IDC_COMBO1                      1255
#define IDC_RADIO1                      1256
#define IDC_REC_GBA                     1257
#define IDC_REC_GBC                     1258
#define IDC_REC_SGB                     1259
#define IDC_REC_SGB2                    1260
#define IDC_REC_GB                      1261
#define IDC_EDIT_PAUSEFRAME             1262
#define IDC_CHECK_PAUSEFRAME            1263
#define IDC_SLIDER1                     1264
#define IDC_CHECK_HIDEBORDER            1265
#define IDC_RADIO_WHITE                 1266
#define IDC_RADIO_RED                   1267
#define IDC_RADIO_YELLOW                1268
#define IDC_RADIO_GREEN                 1269
#define IDC_RADIO_CYAN                  1270
#define IDC_RADIO_BLUE                  1271
#define IDC_RADIO_MAGENTA               1272
#define IDC_RADIO_BLACK                 1273
#define IDC_CHECK_OUTLINED              1274
#define IDC_CHECK_TRANSPARENT           1275
#define IDC_RADIO_PREFILTER             1276
#define IDC_RADIO_POSTFILTER            1277
#define IDC_RADIO_POSTRENDER            1278
#define IDC_COMMANDS_HIDDEN             1279
#define IDC_DECIMAL_DISPLAY             1281
#define IDC_ALIGN                       1282
#define IDC_CHEATREFRESHBUTTON          1283
#define IDC_EDIT_LUAPATH                1285
#define IDC_BUTTON_LUABROWSE            1286
#define IDC_PLUGIN_DIR                  1308
#define IDC_WATCH_DIR                   1309
#define IDC_ROM_DIR                     1310
#define IDC_GBXROM_DIR                  1311
#define IDC_BATTERY_DIR                 1312
#define IDC_SAVE_DIR                    1313
#define IDC_MOVIE_DIR                   1314
#define IDC_CHEAT_DIR                   1315
#define IDC_LUA_DIR                     1316
#define IDC_AVI_DIR                     1317
#define IDC_WAV_DIR                     1318
#define IDC_CAPTURE_DIR                 1319
#define IDC_IPS_DIR                     1320
#define IDC_PLUGIN_PATH                 1328
#define IDC_WATCH_PATH                  1329
#define IDC_ROM_PATH                    1330
#define IDC_GBXROM_PATH                 1331
#define IDC_BATTERY_PATH                1332
#define IDC_SAVE_PATH                   1333
#define IDC_MOVIE_PATH                  1334
#define IDC_CHEAT_PATH                  1335
#define IDC_LUA_PATH                    1336
#define IDC_AVI_PATH                    1337
#define IDC_WAV_PATH                    1338
#define IDC_CAPTURE_PATH                1339
#define IDC_IPS_PATH                    1340
#define IDC_PLUGIN_DIR_RESET            1348
#define IDC_WATCH_DIR_RESET             1349
#define IDC_ROM_DIR_RESET               1350
#define IDC_GBXROM_DIR_RESET            1351
#define IDC_BATTERY_DIR_RESET           1352
#define IDC_SAVE_DIR_RESET              1353
#define IDC_MOVIE_DIR_RESET             1354
#define IDC_CHEAT_DIR_RESET             1355
#define IDC_LUA_DIR_RESET               1356
#define IDC_AVI_DIR_RESET               1357
#define IDC_WAV_DIR_RESET               1358
#define IDC_CAPTURE_DIR_RESET           1359
#define IDC_IPS_DIR_RESET               1360
#define IDC_LIST1                       1361
#define IDC_BUTTON_LUARUN               1362
#define IDC_BUTTON_LUASTOP              1363
#define IDC_LUACONSOLE                  1364
#define IDC_BUTTON_LUAEDIT              1365
#define IDC_LUACONSOLE_CLEAR            1366
#define IDC_LUACONSOLE_CHOOSEFONT       1367
#define IDC_ACCELEDIT_APPLY             1368
#define IDC_ACCELEDIT_SELECTALL         1369
#define IDC_ACCELEDIT_REPLACE           1370
#define IDC_ACCELEDIT_ONFLYKEYEDIT      1371
#define IDC_ACCELEDIT_PROGRESSBAR       1372
#define IDC_ACCELEDIT_AUTOTIMEOUT       1373
#define IDC_ACCELEDIT_UNDO              1374
#define IDC_STATIC5                     1375
#define IDC_BIT_0                       1380
#define IDC_BIT_1                       1381
#define IDC_BIT_2                       1382
#define IDC_BIT_3                       1383
#define IDC_BIT_4                       1384
#define IDC_BIT_5                       1385
#define IDC_BIT_6                       1386
#define IDC_BIT_7                       1387
#define IDC_BIT_8                       1388
#define IDC_BIT_9                       1389
#define IDC_BIT_10                      1390
#define IDC_BIT_11                      1391
#define IDC_BIT_12                      1392
#define IDC_BIT_13                      1393
#define IDC_BIT_14                      1394
#define IDC_BIT_15                      1395
#define IDC_READONLY                    1398
#define IDC_EDIT_AUTHOR                 1399
#define IDC_EDIT_DESCRIPTION            1400
#define IDC_RECNOW                      1401
#define IDC_RECRESET                    1402
#define IDC_RECSTART                    1403
#define IDC_REC_NOBIOS                  1404
#define IDC_REC_EMUBIOS                 1405
#define IDC_REC_GBABIOS                 1406
#define IDC_REC_GBABIOSINTRO            1407
#define IDC_MOVIE_FILENAME              1408
#define IDC_MOVIE_REFRESH               1409
#define IDC_LABEL_DATE                  1410
#define IDC_LABEL_LENGTH                1411
#define IDC_LABEL_FRAMES                1412
#define IDC_LABEL_RERECORD              1413
#define IDC_LABEL_FROM                  1414
#define IDC_LABEL_WARNING1              1416
#define IDC_LABEL_WARNING2              1417
#define IDC_LABEL_FROM2                 1418
#define IDC_VERSION                     1419
#define IDC_EDIT_UP                     1420
#define IDC_EDIT_DOWN                   1421
#define IDC_EDIT_LEFT                   1422
#define IDC_EDIT_RIGHT                  1423
#define IDC_EDIT_BUTTON_A               1424
#define IDC_EDIT_BUTTON_B               1425
#define IDC_EDIT_BUTTON_SELECT          1426
#define IDC_EDIT_BUTTON_START           1427
#define IDC_EDIT_SPEED                  1430
#define IDC_EDIT_CAPTURE                1431
#define IDC_EDIT_BUTTON_L               1432
#define IDC_EDIT_BUTTON_GS              1433
#define IDC_EDIT_BUTTON_R               1434
#define IDC_ADD_CHEAT                   1440
#define IDC_ADD_GS_CHEAT                1441
#define IDC_ADD_GAMESHARK               1445
#define IDC_JOYPAD1                     1453
#define IDC_JOYPAD2                     1454
#define IDC_JOYPAD3                     1455
#define IDC_JOYPAD4                     1456
#define IDC_FLIP                        1457
#define IDC_PALETTE_NUM                 1458
#define IDC_TILE_NUM                    1459
#define ID_OK                           32771
#define ID_CANCEL                       32772
#define ID_SAVE                         32773
#define ID_PRINT                        32774
#define ID_HELP_ABOUT                   40001
#define ID_FILE_EXIT                    40002
#define ID_OPTIONS_SOUND_MUTE           40003
#define ID_OPTIONS_VIDEO_VSYNC          40009
#define ID_OPTIONS_VIDEO_X1             40010
#define ID_OPTIONS_VIDEO_X2             40011
#define ID_OPTIONS_VIDEO_X3             40012
#define ID_OPTIONS_VIDEO_X4             40013
#define ID_FILE_PAUSE                   40014
#define ID_OPTIONS_EMULATOR_DIRECTORIES 40015
#define ID_OPTIONS_JOYPAD               40016
#define ID_OPTIONS_EMULATOR_SYNCHRONIZE 40017
#define ID_FILE_RESET                   40018
#define ID_FILE_LOAD                    40019
#define ID_OPTIONS_SOUND_DIRECTSOUNDA   40020
#define ID_OPTIONS_SOUND_DIRECTSOUNDB   40021
#define ID_OPTIONS_SOUND_DISABLE        40022
#define ID_OPTIONS_SOUND_OFF            40023
#define ID_OPTIONS_SOUND_ON             40024
#define ID_OPTIONS_SOUND_CHANNEL1       40025
#define ID_OPTIONS_SOUND_CHANNEL2       40026
#define ID_OPTIONS_SOUND_CHANNEL3       40027
#define ID_OPTIONS_SOUND_CHANNEL4       40028
#define ID_OPTIONS_EMULATOR_USEBIOSFILE 40029
#define ID_OPTIONS_EMULATOR_SELECTBIOSFILE 40030
#define ID_CHEATS_SEARCHFORCHEATS       40031
#define ID_CHEATS_ADDCHEAT              40032
#define ID_OPTIONS_VIDEO_DISABLESFX     40033
#define ID_OPTIONS_GAMEBOY_BORDER       40034
#define ID_FILE_SAVEGAME_SLOT1          40035
#define ID_FILE_SAVEGAME_SLOT2          40036
#define ID_FILE_SAVEGAME_SLOT3          40037
#define ID_FILE_SAVEGAME_SLOT4          40038
#define ID_FILE_SAVEGAME_SLOT5          40039
#define ID_FILE_SAVEGAME_SLOT6          40040
#define ID_FILE_SAVEGAME_SLOT7          40041
#define ID_FILE_SAVEGAME_SLOT8          40042
#define ID_FILE_SAVEGAME_SLOT9          40043
#define ID_FILE_SAVEGAME_SLOT10         40044
#define ID_FILE_LOADGAME_SLOT1          40045
#define ID_FILE_LOADGAME_SLOT2          40046
#define ID_FILE_LOADGAME_SLOT3          40047
#define ID_FILE_LOADGAME_SLOT4          40048
#define ID_FILE_LOADGAME_SLOT5          40049
#define ID_FILE_LOADGAME_SLOT6          40050
#define ID_FILE_LOADGAME_SLOT7          40051
#define ID_FILE_LOADGAME_SLOT8          40052
#define ID_FILE_LOADGAME_SLOT9          40053
#define ID_FILE_LOADGAME_SLOT10         40054
#define ID_OPTIONS_GAMEBOY_AUTOMATIC    40057
#define ID_OPTIONS_GAMEBOY_CGB          40058
#define ID_OPTIONS_GAMEBOY_GBA          40059
#define ID_OPTIONS_GAMEBOY_SGB          40060
#define ID_OPTIONS_GAMEBOY_GB           40062
#define ID_OPTIONS_GAMEBOY_REALCOLORS   40063
#define ID_OPTIONS_GAMEBOY_GAMEBOYCOLORS 40064
#define ID_CHEATS_GAMEBOY               40065
#define ID_OPTIONS_SOUND_11KHZ          40067
#define ID_OPTIONS_SOUND_22KHZ          40068
#define ID_OPTIONS_SOUND_44KHZ          40069
#define ID_OPTIONS_VIDEO_DDRAWEMULATIONONLY 40070
#define ID_OPTIONS_VIDEO_DDRAWUSEVIDEOMEMORY 40071
#define ID_OPTIONS_PRIORITY_HIGHEST     40072
#define ID_OPTIONS_PRIORITY_ABOVENORMAL 40073
#define ID_OPTIONS_PRIORITY_NORMAL      40074
#define ID_OPTIONS_PRIORITY_BELOWNORMAL 40075
#define ID_OPTIONS_VIDEO_FULLSCREEN320X240 40076
#define ID_OPTIONS_VIDEO_FULLSCREEN640X480 40077
#define ID_OPTIONS_FILTER_NORMAL        40078
#define ID_OPTIONS_FILTER_2XSAI         40079
#define ID_OPTIONS_FILTER_SUPER2XSAI    40081
#define ID_OPTIONS_FILTER_SUPEREAGLE    40082
#define ID_OPTIONS_FILTER_TVMODE        40083
#define ID_CHEATS_CHEATLIST             40084
#define ID_OPTIONS_JOYPAD_AUTOFIRE_A_OLD 40085
#define ID_OPTIONS_JOYPAD_AUTOFIRE_B_OLD 40086
#define ID_OPTIONS_JOYPAD_AUTOFIRE_L_OLD 40087
#define ID_OPTIONS_JOYPAD_AUTOFIRE_R_OLD 40088
#define ID_OPTIONS_VIDEO_FULLSCREENSTRETCHTOFIT 40089
#define ID_OPTIONS_EMULATOR_ASSOCIATE   40091
#define ID_OPTIONS_FILTER_DISABLEMMX    40093
#define ID_OPTIONS_1X                   40096
#define ID_OPTIONS_2X                   40097
#define ID_OPTIONS_3X                   40098
#define ID_OPTIONS_4X                   40099
#define ID_FILE_ROMINFORMATION          40100
#define ID_CHEATS_ADDCHEATCODE          40101
#define ID_OPTIONS_VIDEO_DISABLESTATUSMESSAGES 40102
#define ID_OPTIONS_JOYPAD_MOTIONCONFIGURE 40103
#define ID_FILE_SCREENCAPTURE           40104
#define ID_OPTIONS_LANGUAGE_SYSTEM      40105
#define ID_OPTIONS_LANGUAGE_ENGLISH     40106
#define ID_OPTIONS_LANGUAGE_OTHER       40107
#define ID_OPTIONS_GAMEBOY_PRINTER      40108
#define ID_FILE_RECENT_RESET            40109
#define ID_CHEATS_SAVECHEATLIST         40110
#define ID_CHEATS_LOADCHEATLIST         40111
#define ID_CHEATS_AUTOMATICSAVELOADCHEATS 40112
#define ID_FILE_IMPORT_GAMESHARKSNAPSHOT 40115
#define ID_FILE_IMPORT_BATTERYFILE      40116
#define ID_FILE_IMPORT_GAMESHARKCODEFILE 40117
#define ID_FILE_EXPORT_BATTERYFILE      40118
#define ID_OPTIONS_FILTER16BIT_PIXELATEEXPERIMENTAL 40121
#define ID_OPTIONS_FILTER16BIT_MOTIONBLUREXPERIMENTAL 40122
#define ID_OPTIONS_EMULATOR_PAUSEWHENINACTIVE 40123
#define ID_TOOLS_SOUNDRECORDING         40124
#define ID_OPTIONS_VIDEO_LAYERS_BG0     40127
#define ID_OPTIONS_VIDEO_LAYERS_BG1     40128
#define ID_OPTIONS_VIDEO_LAYERS_BG2     40129
#define ID_OPTIONS_VIDEO_LAYERS_BG3     40130
#define ID_OPTIONS_VIDEO_LAYERS_OBJ     40131
#define ID_OPTIONS_VIDEO_LAYERS_WIN0    40132
#define ID_OPTIONS_VIDEO_LAYERS_WIN1    40133
#define ID_OPTIONS_VIDEO_LAYERS_OBJWIN  40134
#define ID_FILE_OPENGAMEBOY             40135
#define ID_OPTIONS_SOUND_USEOLDSYNCHRONIZATION 40136
#define ID_DEBUG_NEXTFRAME              40137
#define ID_TOOLS_MAPVIEW                40138
#define ID_TOOLS_PALETTEVIEW            40139
#define ID_OPTIONS_EMULATOR_PNGFORMAT   40140
#define ID_OPTIONS_EMULATOR_BMPFORMAT   40141
#define ID_TOOLS_CUSTOMIZE_COMMON       40142
#define ID_TOOLS_MEMORYVIEWER           40143
#define ID_TOOLS_OAMVIEWER              40144
#define ID_TOOLS_TILEVIEWER             40146
#define ID_OPTIONS_GAMEBOY_COLORS       40147
#define ID_OPTIONS_SOUND_ECHO           40148
#define ID_OPTIONS_SOUND_LOWPASSFILTER  40149
#define ID_OPTIONS_SOUND_REVERSESTEREO  40150
#define ID_TOOLS_DISASSEMBLE            40151
#define ID_TOOLS_DEBUG_GDB              40152
#define ID_TOOLS_DEBUG_LOADANDWAIT      40153
#define ID_TOOLS_DEBUG_DISCONNECT       40154
#define ID_TOOLS_DEBUG_BREAK            40155
#define ID_TOOLS_LOGGING                40156
#define ID_OPTIONS_EMULATOR_SPEEDHACK   40157
#define ID_OPTIONS_EMULATOR_SPEEDUPTOGGLE 40158
#define ID_OPTIONS_EMULATOR_REMOVEINTROSGBA 40159
#define ID_OPTIONS_FILTER16BIT_ADVANCEMAMESCALE2X 40160
#define ID_OPTIONS_FILTER16BIT_SIMPLE2X 40161
#define ID_FILE_RECENT_FREEZE           40162
#define ID_FILE_EXPORT_GAMESHARKSNAPSHOT 40163
#define ID_OPTIONS_VIDEO_FULLSCREEN800X600 40164
#define ID_OPTIONS_FILTER16BIT_SIMPLE3X 40165
#define ID_OPTIONS_FILTER16BIT_SIMPLE4X 40166
#define ID_OPTIONS_FILTER16BIT_PIXELATEEXPERIMENTAL3X 40167
#define ID_OPTIONS_FILTER16BIT_PIXELATEEXPERIMENTAL4X 40168
#define ID_OPTIONS_EMULATOR_SAVETYPE_AUTOMATIC 40169
#define ID_OPTIONS_EMULATOR_SAVETYPE_EEPROM 40170
#define ID_OPTIONS_EMULATOR_SAVETYPE_SRAM 40171
#define ID_OPTIONS_EMULATOR_SAVETYPE_FLASH 40172
#define ID_OPTIONS_EMULATOR_SAVETYPE_EEPROMSENSOR 40173
#define ID_OPTIONS_EMULATOR_SAVETYPE_FLASH512K 40174
#define ID_OPTIONS_EMULATOR_SAVETYPE_FLASH1M 40175
#define ID_OPTIONS_EMULATOR_AUTOMATICALLYIPSPATCH 40176
#define ID_TOOLS_AVIRECORDING           40177
#define ID_OPTIONS_SOUND_VOLUME_1X      40182
#define ID_OPTIONS_SOUND_VOLUME_2X      40183
#define ID_OPTIONS_SOUND_VOLUME_3X      40184
#define ID_OPTIONS_SOUND_VOLUME_4X      40185
#define ID_OPTIONS_FILTER_BILINEAR      40186
#define ID_OPTIONS_FILTER_BILINEARPLUS  40187
#define ID_OPTIONS_FILTER_INTERFRAMEBLENDING_NONE 40188
#define ID_OPTIONS_FILTER_INTERFRAMEBLENDING_MOTIONBLUR 40189
#define ID_OPTIONS_FILTER_INTERFRAMEBLENDING_SMART 40190
#define ID_OPTIONS_VIDEO_FULLSCREEN     40191
#define ID_OPTIONS_VIDEO_TRIPLEBUFFERING 40192
#define ID_OPTIONS_FRAMESKIP_AUTOMATIC  40194
#define ID_OPTIONS_EMULATOR_SHOWSPEED_NONE 40195
#define ID_OPTIONS_EMULATOR_SHOWSPEED_PERCENTAGE 40196
#define ID_OPTIONS_EMULATOR_SHOWSPEED_DETAILED 40197
#define ID_OPTIONS_EMULATOR_SHOWSPEED_TRANSPARENT 40198
#define ID_OPTIONS_JOYPAD_CONFIGURE_1   40199
#define ID_OPTIONS_JOYPAD_CONFIGURE_2   40200
#define ID_OPTIONS_JOYPAD_CONFIGURE_3   40201
#define ID_OPTIONS_JOYPAD_CONFIGURE_4   40202
#define ID_OPTIONS_JOYPAD_DEFAULTJOYPAD_1 40208
#define ID_OPTIONS_JOYPAD_DEFAULTJOYPAD_2 40209
#define ID_OPTIONS_JOYPAD_DEFAULTJOYPAD_3 40210
#define ID_OPTIONS_JOYPAD_DEFAULTJOYPAD_4 40211
#define ID_OPTIONS_EMULATOR_STORESETTINGSINREGISTRY 40214
#define ID_FILE_EXPORT_SETTINGSTOINI    40215
#define ID_OPTIONS_FRAMESKIP_THROTTLE_NOTHROTTLE 40216
#define ID_OPTIONS_FRAMESKIP_THROTTLE_OTHER 40221
#define ID_SYSTEM_MAXIMIZE              40222
#define ID_OPTIONS_FILTER_SCANLINES     40223
#define ID_OPTIONS_VIDEO_RENDERMETHOD_GDI 40228
#define ID_OPTIONS_VIDEO_RENDERMETHOD_DIRECTDRAW 40229
#define ID_OPTIONS_VIDEO_RENDERMETHOD_DIRECT3D 40230
#define ID_OPTIONS_VIDEO_RENDERMETHOD_OPENGL 40231
#define ID_OPTIONS_VIDEO_RENDEROPTIONS_D3DNOFILTER 40233
#define ID_OPTIONS_VIDEO_RENDEROPTIONS_D3DBILINEAR 40234
#define ID_OPTIONS_VIDEO_RENDEROPTIONS_D3DTRILINEAR 40235
#define ID_OPTIONS_VIDEO_RENDEROPTIONS_D3DANISOTROPIC 40236
#define ID_OPTIONS_VIDEO_RENDEROPTIONS_GLNEAREST 40237
#define ID_OPTIONS_VIDEO_RENDEROPTIONS_GLBILINEAR 40238
#define ID_OPTIONS_VIDEO_RENDEROPTIONS_GLTRIANGLE 40239
#define ID_OPTIONS_VIDEO_RENDEROPTIONS_GLQUADS 40240
#define ID_OPTIONS_VIDEO_RENDEROPTIONS_SELECTSKIN 40245
#define ID_OPTIONS_VIDEO_RENDEROPTIONS_SKIN 40246
#define ID_OPTIONS_EMULATOR_AGBPRINT    40247
#define ID_OPTIONS_EMULATOR_REALTIMECLOCK 40248
#define ID_OPTIONS_GAMEBOY_SGB2         40249
#define ID_SYSTEM_MINIMIZE              40250
#define ID_MOVIE_RECORD                 40251
#define ID_MOVIE_PLAY                   40253
#define ID_MOVIE_STOP                   40254
#define ID_OPTIONS_EMULATOR_AUTOHIDEMENU 40255
#define ID_OPTIONS_GAMEBOY_BORDERAUTOMATIC 40256
#define ID_OPTIONS_EMULATOR_REWIND      40257
#define ID_TOOLS_REWIND                 40258
#define ID_OPTIONS_EMULATOR_SKIPBIOS    40259
#define ID_HELP_BUGREPORT               40260
#define ID_HELP_FAQ                     40261
#define ID_OPTIONS_EMULATOR_REWINDINTERVAL 40262
#define ID_FILE_TOGGLEMENU              40263
#define ID_OPTIONS_EMULATOR_SAVETYPE_NONE 40264
#define ID_OPTIONS_EMULATOR_SAVETYPE_ENHANCEDDETECTION 40265
#define ID_TOOLS_IOVIEWER               40266
#define ID_OPTIONS_SOUND_VOLUME_5X      40270
#define ID_OPTIONS_SOUND_VOLUME_25X     40271
#define ID_CHEATS_DISABLECHEATS         40272
#define ID_OPTIONS_VIDEO_FULLSCREENMAXSCALE 40273
#define ID_OPTIONS_FILTER_LQ2X          40275
#define ID_OPTIONS_FILTER_HQ2X          40276
#define ID_OPTIONS_FILTER_HQ2X2         40277
#define ID_OPTIONS_FILTER_HQ3X          40278
#define ID_OPTIONS_FILTER_HQ3X2         40279
#define ID_OPTIONS_FRAMESKIP_ACCURATEPITCH 40289
#define ID_OPTIONS_FRAMESKIP_ACCURATESPEED 40290
#define ID_OPTIONS_FRAMESKIP_THROTTLE_6 40324
#define ID_OPTIONS_FRAMESKIP_THROTTLE_15 40325
#define ID_OPTIONS_FRAMESKIP_THROTTLE_25 40326
#define ID_OPTIONS_FRAMESKIP_THROTTLE_37 40327
#define ID_OPTIONS_FRAMESKIP_THROTTLE_50 40328
#define ID_OPTIONS_FRAMESKIP_THROTTLE_75 40329
#define ID_OPTIONS_FRAMESKIP_THROTTLE_87 40330
#define ID_OPTIONS_FRAMESKIP_THROTTLE_100 40331
#define ID_OPTIONS_FRAMESKIP_THROTTLE_112 40332
#define ID_OPTIONS_FRAMESKIP_THROTTLE_125 40333
#define ID_OPTIONS_FRAMESKIP_THROTTLE_150 40334
#define ID_OPTIONS_FRAMESKIP_THROTTLE_200 40335
#define ID_OPTIONS_FRAMESKIP_THROTTLE_300 40336
#define ID_OPTIONS_FRAMESKIP_THROTTLE_400 40337
#define ID_OPTIONS_FRAMESKIP_THROTTLE_600 40338
#define ID_OPTIONS_FRAMESKIP_THROTTLE_800 40339
#define ID_OPTIONS_FRAMESKIP_THROTTLE_1000 40340
#define ID_TOOLS_FRAMECOUNTER           40341
#define ID_TOOLS_INPUTDISPLAY           40342
#define ID_OPTIONS_VIDEO_FRAMESKIP_0    40350
#define ID_OPTIONS_VIDEO_FRAMESKIP_1    40351
#define ID_OPTIONS_VIDEO_FRAMESKIP_2    40352
#define ID_OPTIONS_VIDEO_FRAMESKIP_3    40353
#define ID_OPTIONS_VIDEO_FRAMESKIP_4    40354
#define ID_OPTIONS_VIDEO_FRAMESKIP_5    40355
#define ID_OPTIONS_VIDEO_FRAMESKIP_6    40356
#define ID_OPTIONS_VIDEO_FRAMESKIP_7    40357
#define ID_OPTIONS_VIDEO_FRAMESKIP_8    40358
#define ID_OPTIONS_VIDEO_FRAMESKIP_9    40359
#define ID_OPTIONS_FRAMESKIP_THROTTLE_INCREASE 40364
#define ID_OPTIONS_FRAMESKIP_THROTTLE_DECREASE 40365
#define ID_OPTIONS_JOYPAD_AUTOFIRE_A    40366
#define ID_OPTIONS_JOYPAD_AUTOFIRE_B    40367
#define ID_OPTIONS_JOYPAD_AUTOFIRE_L    40368
#define ID_OPTIONS_JOYPAD_AUTOFIRE_R    40369
#define ID_OPTIONS_JOYPAD_AUTOFIRE_START 40370
#define ID_OPTIONS_JOYPAD_AUTOFIRE_SELECT 40371
#define ID_OPTIONS_JOYPAD_AUTOFIRE_UP   40372
#define ID_OPTIONS_JOYPAD_AUTOFIRE_DOWN 40373
#define ID_OPTIONS_JOYPAD_AUTOFIRE_LEFT 40374
#define ID_OPTIONS_JOYPAD_AUTOFIRE_RIGHT 40375
#define ID_OPTIONS_JOYPAD_AUTOFIRE_CLEAR 40376
#define ID_OPTIONS_SOUND_MUTEFRAMEADVANCE 40378
#define ID_OPTIONS_JOYPAD_ALLOWLEFTRIGHT 40382
#define ID_MOVIE_READONLY               40385
#define ID_MOVIE_RESTART_PLAY           40387
#define ID_MOVIE_RESUME_RECORD          40388
#define ID_FILE_LOADGAME_AUTOLOADMOSTRECENT 40393
#define ID_EMULATOR_GBALAG              40394
#define ID_EMULATOR_USE_OLD_FRAME_TIMING 40395
#define ID_EMULATOR_USE_GB_INPUT_HACK   40396
#define ID_OPTIONS_VIDEO_TEXTDISPLAYOPTIONS 40397
#define ID_EMULATION_V20_GB_FRAME_HACK  40398
#define ID_STICKY_A                     40399
#define ID_STICKY_B                     40400
#define ID_STICKY_R                     40402
#define ID_STICKY_START                 40403
#define ID_STICKY_SELECT                40404
#define ID_STICKY_UP                    40405
#define ID_STICKY_DOWN                  40406
#define ID_STICKY_LEFT                  40407
#define ID_STICKY_RIGHT                 40408
#define ID_STICKY_L                     40410
#define ID_STICKY_CLEAR                 40412
#define ID_FILE_SAVEGAME_DECREMENTSLOT  40416
#define ID_FILE_LOADGAME_MOSTRECENT     40420
#define ID_FILE_LOADGAME_CURRENT        40423
#define ID_FILE_LOADGAME_MAKECURRENT    40424
#define ID_FILE_SAVEGAME_CURRENT        40427
#define ID_FILE_SAVEGAME_MAKECURRENT    40428
#define ID_FILE_SAVEGAME_OLDESTSLOT     40429
#define ID_FILE_SAVEGAME_INCREMENTSLOT  40430
#define ID_FILE_LOADGAME_MAKERECENT     40431
#define ID_DEBUG_FRAMESEARCH            40432
#define ID_DEBUG_FRAMESEARCHLOAD        40438
#define ID_DEBUG_FRAMESEARCHPREV        40439
#define ID_SELECT_SLOT1                 40440
#define ID_SELECT_SLOT2                 40441
#define ID_SELECT_SLOT3                 40442
#define ID_SELECT_SLOT4                 40443
#define ID_SELECT_SLOT5                 40444
#define ID_SELECT_SLOT6                 40445
#define ID_SELECT_SLOT7                 40446
#define ID_SELECT_SLOT8                 40447
#define ID_SELECT_SLOT9                 40448
#define ID_SELECT_SLOT10                40449
#define ID_TOOLS_DEBUG                  40450
#define ID_TOOLS_CUSTOMIZE              40452
#define ID_OPTIONS_SPEED                40453
#define ID_SPEED_BLA                    40454
#define ID_SPEED_FRAMESKIP              40455
#define ID_FRAMESKIP_BLA                40456
#define ID_SPEED_SETSPEED               40457
#define ID_SETSPEED_BLA                 40458
#define ID_SOUND_SOUNDCHANNELS          40459
#define ID_CHEATS_PAUSEDURINGCHEATSEARCH 40463
#define ID_TOOLS_LAGCOUNTER             40464
#define ID_FILE_LUA_OPEN                40467
#define ID_FILE_LUA_RELOAD              40468
#define ID_FILE_LUA_CLOSE_ALL           40469
#define ID_TOOLS_LAGCOUNTER_RESET       40470
#define ID_FILE_QUICKSCREENCAPTURE      40471
#define ID_MOVIE_END_EXIT               40480
#define ID_MOVIE_END_RESET              40481
#define ID_MOVIE_END_CLOSE              40482
#define ID_MOVIE_END_OPENGBA            40483
#define ID_MOVIE_END_OPENGBX            40484
#define ID_MOVIE_END_LOADGAME           40485
#define ID_MOVIE_END_SAVEGAME           40486
#define ID_MOVIE_END_PAUSE              40487
#define ID_MOVIE_END_RESTART            40488
#define ID_MOVIE_END_APPEND             40489
#define ID_MOVIE_END_STOP               40490
#define ID_MOVIE_END_KEEP               40491
#define ID_MOVIE_END_PLAY               40492
#define ID_MOVIE_END_NEW                40493
#define ID_MOVIE_TOOL_CONVERT           40501
#define ID_MOVIE_TOOL_TRUNCATE          40504
#define ID_MOVIE_TOOL_FIX_HEADER        40507
#define ID_MOVIE_TOOL_SET_PAUSE_AT      40510
#define ID_RAM_SEARCH                   40522
#define ID_RAM_WATCH                    40523
#define ID_MOVIE_TOOL_AUTO_CONVERT      40541
#define ID_MOVIE_TOOL_EXTRACT_FROM_SAVEGAME 40560
#define ID_MOVIE_TOOL_CONVERT_FILE      40561
#define ID_WATCHES_MOVEUP               40664
#define ID_WATCHES_MOVEDOWN             40665
#define ID_WATCHES_EDITWATCH            40666
#define ID_WATCHES_REMOVEWATCH          40667
#define ID_WATCHES_NEWWATCH             40668
#define ID_WATCHES_DUPLICATEWATCH       40669
#define ID_WATCHES_UPDOWN               40670
#define ID_FILE_LUA_STOP                40671
#define IDC_EDIT_COMPAREVALUE           41090
#define IDC_EDIT_COMPAREADDRESS         41091
#define IDC_EDIT_COMPARECHANGES         41092
#define IDC_EDIT_DIFFBY                 41093
#define IDC_C_AUTOSEARCH                41094
#define IDC_EDIT_MODBY                  41095
#define IDC_RAMLIST                     41133
#define IDC_C_SEARCH                    41134
#define IDC_C_ADDCHEAT                  41135
#define IDC_C_RESET                     41136
#define IDC_1_BYTE                      41137
#define IDC_2_BYTES                     41138
#define IDC_C_WATCH                     41139
#define IDC_4_BYTES                     41140
#define IDC_LESSTHAN                    41141
#define IDC_MORETHAN                    41142
#define IDC_NOMORETHAN                  41143
#define IDC_NOLESSTHAN                  41144
#define IDC_EQUALTO                     41145
#define IDC_DIFFERENTFROM               41146
#define IDC_DIFFERENTBY                 41147
#define IDC_MODULO                      41148
#define IDC_HEX                         41151
#define IDC_C_UNDO                      41152
#define IDC_C_RESET_CHANGES             41153
#define IDC_PREVIOUSVALUE               42147
#define IDC_SPECIFICVALUE               42148
#define IDC_CHEATEDITVALUE              42156
#define IDC_SPECIFICADDRESS             42157
#define IDC_NUMBEROFCHANGES             42158
#define IDC_MISALIGN                    42159
#define IDC_WATCHLIST                   42171
#define IDC_C_ELIMINATE                 42174
#define RAMMENU_FILE_AUTOLOAD           42300
#define RAMMENU_FILE_APPEND             42301
#define RAMMENU_FILE_SAVEWINDOW         42302
#define RAMMENU_FILE_NEW                42303
#define RAMMENU_FILE_OPEN               42304
#define RAMMENU_FILE_SAVE               42305
#define RAMMENU_FILE_SAVEAS             42306
#define RAMMENU_FILE_RECENT             42307
#define RW_MENU_FIRST_RECENT_FILE       42350
#define RW_MENU_LAST_RECENT_FILE        42370
#define ID_OPTIONS_PREFER_ARCHIVE_NAME  42400
#define ID_OPTIONS_PREFER_ROM_NAME      42401
#define ID_OPTIONS_EMULATOR_ALWAYSONTOP 42402
#define ID_OPTIONS_EMULATOR_BACKGROUNDINPUT 42403
#define ID_OPTIONS_SOUND_MUTEWHENINACTIVE 42404
#define ID_FILE_SLOT_DISPLAYMODIFICATIONTIME 42405
#define ID_TOOLS_PAUSEAVIRECORDING      42406
#define ID_AUTO_TAKELAGINTOACCOUNT      42407
#define ID_OPTIONS_JOYPAD_AUTOFIRE_ACCOUNTFORLAG 42408
#define ID_FILE_FRAMEADVANCESETTINGS    42409
#define ID_DEBUG_NEXTFRAME_ACCOUNTFORLAG 42410
#define ID_MOVIE_ASSOCIATEMOVIESWITHSAVESTATES 42411
#define ID_MOVIE_ASSC_WITH_SAVESTATE    42412
#define ID_TOOLS_EXTRACOUNTER           42413
#define ID_TOOLS_EXTRACOUNTERRESET      42415
#define ID_TOOLS_NEXTINPUTDISPLAY       42416
#define ID_MOVIE_TOOL_EDIT_MODE_PREV    42440
#define ID_MOVIE_TOOL_EDIT_MODE_NEXT    42441
#define ID_MOVIE_TOOL_EDIT_MODE_DISCARD 42442
#define ID_MOVIE_TOOL_EDIT_MODE_OVERWRITE 42443
#define ID_MOVIE_TOOL_EDIT_MODE_INSERT  42444
#define ID_MOVIE_TOOL_EDIT_MODE_XOR     42445
#define ID_MOVIE_TOOL_INSERT_ONE_FRAME  42450
#define ID_MOVIE_TOOL_DELETE_ONE_FRAME  42451
#define ID_MOVIE_TOOL_INSERT_FRAMES     42452
#define ID_MOVIE_TOOL_DELETE_FRAMES     42453
#define IDC_C_WATCH_DOWN                43400
#define IDC_C_WATCH_DUPLICATE           43401
#define IDC_C_WATCH_EDIT                43402
#define IDC_C_WATCH_REMOVE              43403
#define IDC_C_WATCH_UP                  43404
#define IDC_C_WATCH_SEPARATE            43405
#define IDC_PROMPT_TEXT                 43410
#define IDC_PROMPT_TEXT2                43411
#define IDC_PROMPT_EDIT                 43412
#define ID_RESET_CONTROLLER 43413

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        193
#define _APS_NEXT_COMMAND_VALUE         42460
#define _APS_NEXT_CONTROL_VALUE         1500
#define _APS_NEXT_SYMED_VALUE           43513
#endif
#endif
