#ifndef VBA_VERSIONINFO_H
#define VBA_VERSIONINFO_H

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "../version.h"

#if SVN_REV > 65535
#	define VBA_RR_BUILD_NO 0
#else
#	define VBA_RR_BUILD_NO SVN_REV
#endif

// diaplayed in the file attribute dialog
#ifdef USE_GBA_CORE_V7
#	define VBA_VERSIONINFO_FILEVER     7, VBA_RR_MAJOR_VERSION_NO, VBA_RR_MINOR_VERSION_NO, VBA_RR_BUILD_NO
#else
#	define VBA_VERSIONINFO_FILEVER     8, VBA_RR_MAJOR_VERSION_NO, VBA_RR_MINOR_VERSION_NO, VBA_RR_BUILD_NO
#endif
#define VBA_VERSIONINFO_STRFILEVER     STRINGIZE_VALUE(VBA_VERSIONINFO_FILEVER) "\0"

#define VBA_VERSIONINFO_PRODUCTVER     VBA_VERSIONINFO_FILEVER
#define VBA_VERSIONINFO_STRPRODUCTVER  VBA_VERSIONINFO_STRFILEVER
#define VBA_VERSIONINFO_STRCOPYRIGHT   "Copyright (C) 2005-2016 VBA-RR Development Team"
#define VBA_VERSIONINFO_ORGANIZATION   VBA_RR_SITE

#ifdef _DEBUG
#	define VBA_VERSIONINFO_FILEFLAGS   VS_FF_DEBUG
#elif defined(PUBLIC_RELEASE)
#	define VBA_VERSIONINFO_FILEFLAGS   0
#else
#	define VBA_VERSIONINFO_FILEFLAGS   VS_FF_PRERELEASE
#endif

#endif // VBA_VERSIONINFO_H
